version: '3.9'

services:
  assessment-service-api:
    build: ./SkillAssessor.AssessmentService.Api/
    restart: always
    depends_on: 
      - "assessment-service-broker"
  
  zookeeper:
      image: confluentinc/cp-zookeeper
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "22181:2181"
      healthcheck:
        test: [ "CMD", "zkServer.sh", "status" ]
        interval: 10s
        timeout: 5s
        retries: 3

  assessment-service-broker:
    image: confluentinc/cp-kafka
    container_name: assessment-service-broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://assessment-service-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1